import { AdminContent, AdminShell } from '@/components/admin-shell'

export default function AttendanceSheetPage() {
  return (
    <AdminShell>
      <AdminContent>
        <div className="space-y-4">
          <h1 className="text-2xl font-semibold tracking-tight">Attendance Sheet</h1>
          <p className="text-sm text-muted-foreground">
            This route is reserved for the attendance sheet generated by the mobile/BLE application.
            The live sheet will be connected here later. Attendance data already lives in the shared PostgreSQL database.
          </p>
        </div>
      </AdminContent>
    </AdminShell>
  )
}
